<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-800 leading-tight">
            {{ __('Latest Posts') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            
            <!-- Grid Layout -->
            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                
                @forelse ($posts as $post)
                    <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg p-6 hover:shadow-md transition-shadow">
                        <h3 class="text-xl font-bold mb-2 text-gray-900">
                            <a href="{{ route('posts.show', $post) }}" class="hover:underline">
                                {{ $post->title }}
                            </a>
                        </h3>
                        <p class="text-gray-500 text-sm mb-4">
                            By {{ $post->user->name }} • {{ $post->created_at->diffForHumans() }}
                        </p>
                        <p class="text-gray-700 mb-4">
                            {{ Str::limit($post->body, 100) }}
                        </p>
                        <a href="{{ route('posts.show', $post) }}" class="text-blue-500 hover:text-blue-700 font-semibold">
                            Read more &rarr;
                        </a>
                    </div>
                @empty
                    <div class="col-span-3 text-center text-gray-500">
                        No posts found yet.
                    </div>
                @endforelse

            </div>

            <!-- Pagination Links (Auto-generated by Laravel) -->
            <div class="mt-6">
                {{ $posts->links() }}
            </div>

        </div>
    </div>
</x-app-layout>